# Generated by Django 3.2.7 on 2021-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_image',
            field=models.CharField(default='Type something!', max_length=1000),
        ),
    ]
