# Generated by Django 3.2.9 on 2021-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('movies', 'movies'), ('antique', 'antique'), ('magical', 'magical'), ('rare item', 'rare item'), ('toys', 'toys'), ('electricals', 'electricals'), ('fashion', 'fashion')], default='movies', max_length=1000),
        ),
    ]
