# Generated by Django 3.2.7 on 2021-11-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211104_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=64)),
                ('listing_id', models.IntegerField()),
                ('comment', models.CharField(default='Type something!', max_length=1000)),
            ],
        ),
    ]
